name = "madrhacks"
license = "MIT"
licenselink = "https://gitlab.com/madrhacks/hugo-madr-theme/blob/master/LICENSE.md"
description = "Our custom theme for MadrHacks site."
tags = ["blog", "clean", "customizable", "dark", "highlighting", "light", "minimal", "monochromatic", "multilingual", "personal", "responsive", "simple", "technical"]
features = ["blog", "shortcode", "syntax highlighting"]
min_version = 0.35

[author]
  name = "MadrHacks Group"
  homepage = "https://madrhacks.org"

[original]
  name = "hello-friend-ng"
  homepage = "https://github.com/rhazdon/hugo-theme-hello-friend-ng"
  repo = "https://github.com/panr/hugo-theme-hello-friend"
